<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "INGENUM");
$APPLICATION->SetTitle("Услуги автоматизации торговли");
?> 
<div class="row"> 
  <div class="col-lg-12"><?$APPLICATION->IncludeComponent(
	"eagle:vacancies.section", 
	"services", 
	array(
		"AJAX_MODE" => "N",
		"SEF_MODE" => "Y",
		"IBLOCK_TYPE" => "1c_catalog",
		"IBLOCK_ID" => "34",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"BROWSER_TITLE" => "-",
		"SET_META_KEYWORDS" => "N",
		"META_KEYWORDS" => "-",
		"SET_META_DESCRIPTION" => "N",
		"META_DESCRIPTION" => "-",
		"ADD_SECTIONS_CHAIN" => "Y",
		"DISPLAY_COMPARE" => "N",
		"SET_STATUS_404" => "N",
		"PAGE_ELEMENT_COUNT" => "9",
		"LINE_ELEMENT_COUNT" => "3",
		"PROPERTY_CODE" => array(
			0 => "TIP_ZASHCHITY",
			1 => "REDAKTSIYA",
			2 => "KOL_VO_RAB_MEST",
			3 => "ADRES_DOSTAVKI",
			4 => "CML2_ARTICLE",
			5 => "CML2_BASE_UNIT",
			6 => "DATA_OPLATY",
			7 => "CML2_MANUFACTURER",
			8 => "CML2_TRAITS",
			9 => "CML2_TAXES",
			10 => "CML2_ATTRIBUTES",
			11 => "CML2_BAR_CODE",
			12 => "EST_ORIGINAL",
			13 => "REG_NOMER_OSNOVNOY_POSTAVKI_1S",
			14 => "REKOMENDUEM",
			15 => "SOVMESTNO",
			16 => "SOTRUDNIK_KONTRAGENTA",
			17 => "DATA_ZAKAZA_NA_SAYTE",
			18 => "NOMER_ZAKAZA_NA_SAYTE",
			19 => "ID_ZVONOK",
			20 => "RAZMER",
			21 => "KACHESTVO",
			22 => "KOLICHESTVO_V_BARABANE",
			23 => "KHARAKTERISTIKA",
			24 => "METOD_OPLATY",
			25 => "METOD_OPLATY_ID",
			26 => "ZAKAZ_OPLACHEN",
			27 => "DOSTAVKA_RAZRESHENA",
			28 => "OTMENEN",
			29 => "FINALNYY_STATUS",
			30 => "STATUS_ZAKAZA",
			31 => "STATUSA_ZAKAZA_ID",
			32 => "DATA_IZMENENIYA_STATUSA",
			33 => "SAYT",
			34 => "ARTIKUL_POSTAVSHCHIKA",
			35 => "VERSIYA",
			36 => "_1S",
			37 => "BESPLATNAYA_DOSTAVKA",
			38 => "BESPLATNAYA_USTANOVKA",
			39 => "BESPLATNAYA_INTEGRATSIYA",
			40 => "UPRAVLYAEMOE_PRILOZHENIE",
			41 => "ITS_PROF_3",
			42 => "SEO_DLYA_1_EDRPOU",
			43 => "ZAKRYTYY_PROGRAMMNYY_KOD",
			44 => "OBYCHNOE_PRILOZHENIE",
			45 => "UNIT_IN",
			46 => "",
		),
		"OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "TAGS",
			5 => "SORT",
			6 => "PREVIEW_TEXT",
			7 => "PREVIEW_PICTURE",
			8 => "DETAIL_TEXT",
			9 => "DETAIL_PICTURE",
			10 => "DATE_ACTIVE_FROM",
			11 => "ACTIVE_FROM",
			12 => "DATE_ACTIVE_TO",
			13 => "ACTIVE_TO",
			14 => "SHOW_COUNTER",
			15 => "SHOW_COUNTER_START",
			16 => "IBLOCK_TYPE_ID",
			17 => "IBLOCK_ID",
			18 => "IBLOCK_CODE",
			19 => "IBLOCK_NAME",
			20 => "IBLOCK_EXTERNAL_ID",
			21 => "DATE_CREATE",
			22 => "CREATED_BY",
			23 => "CREATED_USER_NAME",
			24 => "TIMESTAMP_X",
			25 => "MODIFIED_BY",
			26 => "USER_NAME",
			27 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "TIP_ZASHCHITY",
			1 => "REDAKTSIYA",
			2 => "KOL_VO_RAB_MEST",
			3 => "ADRES_DOSTAVKI",
			4 => "CML2_ARTICLE",
			5 => "CML2_BASE_UNIT",
			6 => "DATA_OPLATY",
			7 => "MORE_PHOTO",
			8 => "CML2_MANUFACTURER",
			9 => "CML2_TRAITS",
			10 => "CML2_TAXES",
			11 => "FILES",
			12 => "CML2_ATTRIBUTES",
			13 => "CML2_BAR_CODE",
			14 => "EST_ORIGINAL",
			15 => "REG_NOMER_OSNOVNOY_POSTAVKI_1S",
			16 => "REKOMENDUEM",
			17 => "SOVMESTNO",
			18 => "SOTRUDNIK_KONTRAGENTA",
			19 => "DATA_ZAKAZA_NA_SAYTE",
			20 => "NOMER_ZAKAZA_NA_SAYTE",
			21 => "ID_ZVONOK",
			22 => "RAZMER",
			23 => "KACHESTVO",
			24 => "KOLICHESTVO_V_BARABANE",
			25 => "KHARAKTERISTIKA",
			26 => "METOD_OPLATY",
			27 => "METOD_OPLATY_ID",
			28 => "ZAKAZ_OPLACHEN",
			29 => "DOSTAVKA_RAZRESHENA",
			30 => "OTMENEN",
			31 => "FINALNYY_STATUS",
			32 => "STATUS_ZAKAZA",
			33 => "STATUSA_ZAKAZA_ID",
			34 => "DATA_IZMENENIYA_STATUSA",
			35 => "SAYT",
			36 => "ARTIKUL_POSTAVSHCHIKA",
			37 => "VERSIYA",
			38 => "_1S",
			39 => "BESPLATNAYA_DOSTAVKA",
			40 => "BESPLATNAYA_USTANOVKA",
			41 => "BESPLATNAYA_INTEGRATSIYA",
			42 => "UPRAVLYAEMOE_PRILOZHENIE",
			43 => "ITS_PROF_3",
			44 => "SEO_DLYA_1_EDRPOU",
			45 => "ZAKRYTYY_PROGRAMMNYY_KOD",
			46 => "OBYCHNOE_PRILOZHENIE",
			47 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFERS_LIMIT" => "0",
		"PRICE_CODE" => array(
			0 => "Поставка не облагается НДС - SID",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"BASKET_URL" => "/personal/basket.php",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "N",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(
			0 => "TIP_ZASHCHITY",
			1 => "REDAKTSIYA",
			2 => "KOL_VO_RAB_MEST",
			3 => "CML2_MANUFACTURER",
			4 => "CML2_TRAITS",
			5 => "UNIT_IN_PORTFOLIO",
			6 => "UNIT_IN_SOLUTIONS",
			7 => "UNIT_IN_INFO",
			8 => "UNIT_IN_SERVICES",
			9 => "CML2_TAXES",
			10 => "CML2_ATTRIBUTES",
			11 => "SOVMESTNO",
			12 => "SOTRUDNIK_KONTRAGENTA",
			13 => "RAZMER",
			14 => "KACHESTVO",
			15 => "KOLICHESTVO_V_BARABANE",
			16 => "KHARAKTERISTIKA",
			17 => "VERSIYA",
			18 => "PERIOD_PODPISKI",
			19 => "PRODLENIE",
			20 => "KOLICHESTVO_SAYTOV",
			21 => "PEREKHOD_S_REDAKTSII",
			22 => "PEREKHOD_NA_REDAKTSIYU",
			23 => "MODEL",
			24 => "KOMPLEKTATSIYA",
			25 => "PODSISTEMA",
			26 => "MODUL",
			27 => "TIP_PODPISKI",
		),
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_NOTES" => "",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"CONVERT_CURRENCY" => "N",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "TIP_ZASHCHITY",
			1 => "REDAKTSIYA",
			2 => "KOL_VO_RAB_MEST",
			3 => "ADRES_DOSTAVKI",
			4 => "CML2_ARTICLE",
			5 => "CML2_BASE_UNIT",
			6 => "DATA_OPLATY",
			7 => "CML2_MANUFACTURER",
			8 => "CML2_TRAITS",
			9 => "CML2_TAXES",
			10 => "CML2_ATTRIBUTES",
			11 => "CML2_BAR_CODE",
			12 => "EST_ORIGINAL",
			13 => "REG_NOMER_OSNOVNOY_POSTAVKI_1S",
			14 => "REKOMENDUEM",
			15 => "SOVMESTNO",
			16 => "SOTRUDNIK_KONTRAGENTA",
			17 => "DATA_ZAKAZA_NA_SAYTE",
			18 => "NOMER_ZAKAZA_NA_SAYTE",
			19 => "ID_ZVONOK",
			20 => "RAZMER",
			21 => "KACHESTVO",
			22 => "KOLICHESTVO_V_BARABANE",
			23 => "KHARAKTERISTIKA",
			24 => "METOD_OPLATY",
			25 => "METOD_OPLATY_ID",
			26 => "ZAKAZ_OPLACHEN",
			27 => "DOSTAVKA_RAZRESHENA",
			28 => "OTMENEN",
			29 => "FINALNYY_STATUS",
			30 => "STATUS_ZAKAZA",
			31 => "STATUSA_ZAKAZA_ID",
			32 => "DATA_IZMENENIYA_STATUSA",
			33 => "SAYT",
		),
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"SEF_FOLDER" => "/services/",
		"AJAX_OPTION_ADDITIONAL" => "",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?></div>
 </div>
<noindex>
<div id="hypercomments_widget"></div>
 
<script type="text/javascript">
_hcwp = window._hcwp || [];
_hcwp.push({widget:"Stream", widget_id: 22244});
(function() {
if("HC_LOAD_INIT" in window)return;
HC_LOAD_INIT = true;
var lang = (navigator.language || navigator.systemLanguage || navigator.userLanguage || "en").substr(0, 2).toLowerCase();
var hcc = document.createElement("script"); hcc.type = "text/javascript"; hcc.async = true;
hcc.src = ("https:" == document.location.protocol ? "https" : "http")+"://w.hypercomments.com/widget/hc/22244/"+lang+"/widget.js";
var s = document.getElementsByTagName("script")[0];
s.parentNode.insertBefore(hcc, s.nextSibling);
})();
</script>
 <a href="http://hypercomments.com" class="hc-link" title="comments widget" >comments powered by HyperComments</a> 

</noindex>
 <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>